---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toy-be-home
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toy-be-home
  template:
    metadata:
      labels:
        app: toy-be-home
    spec:
      containers:
        - name: toy-be-home
          image: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_home:5ce8222
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
