---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toy-be-home
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toy-be-home
  template:
    metadata:
      labels:
        app: toy-be-home
    spec:
      containers:
        - name: toy-be-home
          #          image: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_home@sha256:b22a79a36a49c71f2b6b5565a7ac11fefe49c54678956accbc70e3481ee6fdd0
          image: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_home:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
